#!/bin/bash
# purgexim - Simple cPanel server script to remove the exim queue
# Intergen 4/12/15
# ---------------------------------------------------------------

function RED {
    tput bold
    tput setaf 1
}
function GREEN {
    tput bold
    tput setaf 2
}
function YELLOW {
    tput bold
    tput setaf 3
}
function BLUE {
    tput bold
    tput setaf 4
}
function SEPARATOR {
    echo
    BLUE
    echo  --------------------------------
    echo
}
function clearline {
    tput cuu 7 && tput el
}

clear
SEPARATOR
GREEN
echo Stopping Exim...
echo
tput sgr0
service exim stop &&
SEPARATOR
GREEN
echo Moving Exim Queue Out of Exim...
mv /var/spool/exim /var/spool/exim.bak &&
SEPARATOR
GREEN
echo Restarting Exim...
echo
tput sgr0
service exim start &&
SEPARATOR
YELLOW
echo Purging Exim Queue
sleep 1
echo
echo This may take awhile...
sleep 1
rm -rf /var/spool/exim.bak &&
clear
SEPARATOR
GREEN
echo Exim Queue Purge Complete
sleep 2
echo
YELLOW
echo Checking for immediate Exim Queue buildup
sleep 1
tput sgr0
printf "(Immediate buildup may indicate further "
RED
printf "SPAM"
tput sgr0
printf " cleanup is required)"
sleep 3
SEPARATOR
count=10
queuecheck=0
today="$(tail -1 /var/log/exim_mainlog | awk '{print $1}')"
while [ $count -gt 0 ]; do
    echo
    YELLOW
    echo Current Exim Queue Size: $(exim -bpc)
    if [ $(exim -bpc) -gt 0 ]; then
        let queuecheck=queuecheck+1
        let count=count-1
        echo
        echo "Exim Queue checks remaining: $count"
        SEPARATOR
        clearline
        sleep 2
    else
        let count=count-1
        echo
        echo "Exim Queue checks remaining: $count"
        SEPARATOR
        clearline
        sleep 2
    fi
done
if [ $queuecheck -gt 2 ]; then
    echo
    RED
    echo Exim Queue grew immediately.  Futher SPAM inspection/cleanup is required.
    echo
    echo "Checking possible SPAM Script Directories..."
    printf "\n\n"
    tput sgr0
    echo "The following directories should be checked for SPAM Scripts:"
    echo "-------------------------------------------------------------"
    echo
    grep cwd /var/log/exim_mainlog | grep "$today" | grep -v /var/spool | awk -F"cwd=" '{print $2}' | awk '{print $1}' | sort | uniq -c | sort -n | tail -5
    printf "\n\n\n"
    echo "The following Exim Log Entries should be checked as well, they may indicate compromised account passwords:"
    echo "----------------------------------------------------------------------------------------------------------"
    mkdir -p /root/support
    exim -bp | awk '{print $3}' >> /root/support/mailids_$(date +"%T_%m-%d-%Y")
    for id in $(cat /root/support/mailids_*); do printf "\n" && grep $id /var/log/exim_mainlog && printf "\n\n"; done
    SEPARATOR
    tput sgr0
    exit 0
else
    echo
    GREEN
    echo The Exim Queue appears to be stable, no further action is needed.
    SEPARATOR
    tput sgr0
    exit 0
fi
